package calculator;

import java.awt.BasicStroke;
import java.awt.Toolkit;
import javax.swing.BorderFactory;

/**
 *
 * @author Sherab Pereira Arias
 * @version 1.0
 */
public class V_Calculator extends javax.swing.JFrame {

    private String currentNumber = "";
    private String charDeleting = "";

    protected String getCurrentNumber() {
        return currentNumber;
    }

    protected void setCurrentNumber(String currentNumber) {
        this.currentNumber = currentNumber;
    }

    protected String getCharDeleting() {
        return charDeleting;
    }

    protected void setCharDeleting(String charDeleting) {
        this.charDeleting = charDeleting;
    }

    protected void concatCurrentNumber(String curNum) {
        if (this.currentNumber == null) {
            this.currentNumber = "";
        }
        this.currentNumber += curNum;
    }

    protected void clearCharDeleting() {
        this.charDeleting = "";
    }

    protected void clearCurrentNumber() {
        this.currentNumber = "";
    }

    /**
     * Creates new form Calculator
     */
    public V_Calculator() {
        initComponents();

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("calcIcon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonSubstraction = new javax.swing.JButton();
        buttonEquals = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonMultiplication = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonComma = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        buttonAddition = new javax.swing.JButton();
        buttonRoot = new javax.swing.JButton();
        buttonPow = new javax.swing.JButton();
        textDisplay = new javax.swing.JTextField();
        button8 = new javax.swing.JButton();
        buttonDivision = new javax.swing.JButton();
        button9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Very Simple Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        buttonSubstraction.setFont(new java.awt.Font("Tlwg Typo", 1, 16)); // NOI18N
        buttonSubstraction.setText("-");
        buttonSubstraction.setFocusPainted(false);
        buttonSubstraction.setMargin(new java.awt.Insets(1, 14, 1, 14));

        buttonEquals.setBackground(new java.awt.Color(0, 118, 35));
        buttonEquals.setFont(new java.awt.Font("Standard Symbols L", 1, 30)); // NOI18N
        buttonEquals.setForeground(new java.awt.Color(255, 255, 255));
        buttonEquals.setText("=");
        buttonEquals.setFocusPainted(false);

        buttonDelete.setBackground(new java.awt.Color(255, 153, 51));
        buttonDelete.setFont(new java.awt.Font("DejaVu Sans", 0, 21)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonDelete.setText("⬅");
        buttonDelete.setFocusPainted(false);

        buttonMultiplication.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        buttonMultiplication.setText("x");
        buttonMultiplication.setFocusPainted(false);
        buttonMultiplication.setMargin(new java.awt.Insets(1, 14, 1, 14));

        button3.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        button3.setText("3");
        button3.setFocusPainted(false);
        button3.setMargin(new java.awt.Insets(1, 14, 1, 14));

        buttonClear.setBackground(new java.awt.Color(255, 51, 0));
        buttonClear.setFont(new java.awt.Font("Umpush", 1, 14)); // NOI18N
        buttonClear.setForeground(new java.awt.Color(255, 255, 255));
        buttonClear.setText("C");
        buttonClear.setFocusPainted(false);
        buttonClear.setMargin(new java.awt.Insets(1, 14, 1, 14));

        button6.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        button6.setText("6");
        button6.setFocusPainted(false);
        button6.setMargin(new java.awt.Insets(1, 14, 1, 14));

        button1.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        button1.setText("1");
        button1.setFocusPainted(false);
        button1.setMargin(new java.awt.Insets(1, 14, 1, 14));

        button2.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        button2.setText("2");
        button2.setFocusPainted(false);
        button2.setMargin(new java.awt.Insets(1, 14, 1, 14));

        button0.setText("0");
        button0.setFocusPainted(false);
        button0.setMargin(new java.awt.Insets(1, 14, 1, 14));

        buttonComma.setFont(new java.awt.Font("Ubuntu Light", 1, 20)); // NOI18N
        buttonComma.setText(".");
        buttonComma.setFocusPainted(false);
        buttonComma.setMargin(new java.awt.Insets(1, 14, 1, 14));

        button7.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        button7.setText("7");
        button7.setFocusPainted(false);
        button7.setMargin(new java.awt.Insets(1, 14, 1, 14));

        button4.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        button4.setText("4");
        button4.setFocusPainted(false);
        button4.setMargin(new java.awt.Insets(1, 14, 1, 14));

        button5.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        button5.setText("5");
        button5.setFocusPainted(false);
        button5.setMargin(new java.awt.Insets(1, 14, 1, 14));

        buttonAddition.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        buttonAddition.setText("+");
        buttonAddition.setFocusPainted(false);
        buttonAddition.setMargin(new java.awt.Insets(1, 14, 1, 14));

        buttonRoot.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        buttonRoot.setText("√");
        buttonRoot.setFocusPainted(false);

        buttonPow.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        buttonPow.setText("x²");
        buttonPow.setFocusPainted(false);

        textDisplay.setEditable(false);
        textDisplay.setBackground(new java.awt.Color(255, 255, 255));
        textDisplay.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        textDisplay.setForeground(new java.awt.Color(51, 51, 51));
        textDisplay.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textDisplay.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), (int)10), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), (int)5)));
        textDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDisplayActionPerformed(evt);
            }
        });

        button8.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        button8.setText("8");
        button8.setFocusPainted(false);
        button8.setMargin(new java.awt.Insets(1, 14, 1, 14));

        buttonDivision.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        buttonDivision.setText("÷");
        buttonDivision.setFocusPainted(false);
        buttonDivision.setMargin(new java.awt.Insets(1, 14, 1, 14));

        button9.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        button9.setText("9");
        button9.setFocusPainted(false);
        button9.setMargin(new java.awt.Insets(1, 14, 1, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textDisplay)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button0, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonComma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(button8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonDivision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                .addComponent(buttonMultiplication, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonAddition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(buttonSubstraction, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonPow, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonEquals, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(textDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonPow, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSubstraction, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonComma, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(buttonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDisplayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonAddition;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonComma;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonDivision;
    private javax.swing.JButton buttonEquals;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonMultiplication;
    private javax.swing.JButton buttonPow;
    private javax.swing.JButton buttonRoot;
    private javax.swing.JButton buttonSubstraction;
    private javax.swing.JTextField textDisplay;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getButton0() {
        return button0;
    }

    public javax.swing.JButton getButton1() {
        return button1;
    }

    public javax.swing.JButton getButton2() {
        return button2;
    }

    public javax.swing.JButton getButton3() {
        return button3;
    }

    public javax.swing.JButton getButton4() {
        return button4;
    }

    public javax.swing.JButton getButton5() {
        return button5;
    }

    public javax.swing.JButton getButton6() {
        return button6;
    }

    public javax.swing.JButton getButton7() {
        return button7;
    }

    public javax.swing.JButton getButton8() {
        return button8;
    }

    public javax.swing.JButton getButton9() {
        return button9;
    }

    public javax.swing.JButton getButtonAddition() {
        return buttonAddition;
    }

    public javax.swing.JButton getButtonClear() {
        return buttonClear;
    }

    public javax.swing.JButton getButtonComma() {
        return buttonComma;
    }

    public javax.swing.JButton getButtonDelete() {
        return buttonDelete;
    }

    public javax.swing.JButton getButtonDivision() {
        return buttonDivision;
    }

    public javax.swing.JButton getButtonEquals() {
        return buttonEquals;
    }

    public javax.swing.JButton getButtonMultiplication() {
        return buttonMultiplication;
    }

    public javax.swing.JButton getButtonPow() {
        return buttonPow;
    }

    public javax.swing.JButton getButtonRoot() {
        return buttonRoot;
    }

    public javax.swing.JButton getButtonSubstraction() {
        return buttonSubstraction;
    }

    public javax.swing.JTextField getTextDisplay() {
        return textDisplay;
    }

    public void setTextDisplay(String newText) {
        this.textDisplay.setText(newText);
    }

}
